# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CinemaTix' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'Kingfisher'
  pod 'FloatingPanel'
  pod 'lottie-ios'
  pod 'SnapKit'
  pod 'AsyncPlus'
  pod 'SwiftIconFont'
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'SkeletonView'
  pod 'RxSwift'
  pod 'Swinject'
  pod 'Cards'

  # Pods for CinemaTix

  target 'CinemaTixTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CinemaTixUITests' do
    # Pods for testing
  end

end
