# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'CinemaTix' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
  pod 'Kingfisher', :git => 'https://github.com/onevcat/Kingfisher.git'
  pod 'FloatingPanel', :git => 'https://github.com/scenee/FloatingPanel.git'
  pod 'lottie-ios', :git => 'https://github.com/airbnb/lottie-ios.git'
  pod 'SnapKit', :git => 'https://github.com/SnapKit/SnapKit.git'
  pod 'SkeletonView', :git => 'https://github.com/Juanpe/SkeletonView.git'
  pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git'
  pod 'RxCocoa', :git => 'https://github.com/ReactiveX/RxSwift.git'
  pod 'Swinject', :git => 'https://github.com/Swinject/Swinject.git'
  pod 'CenteredCollectionView', :git => 'https://github.com/BenEmdon/CenteredCollectionView.git'
  pod 'netfox', :configurations => ['Debug'], :git => 'https://github.com/kasketis/netfox.git'
  pod 'ViewAnimator', :git => 'https://github.com/marcosgriselli/ViewAnimator.git'
  pod 'SPAlert', :git => 'https://github.com/sparrowcode/AlertKit.git'
  pod 'UIKitLivePreview', :git => 'https://github.com/nicoelayda/UIKitLivePreview.git'
  pod 'KeyboardObserver', :git => 'https://github.com/morizotter/KeyboardObserver.git'
  pod 'IQKeyboardManagerSwift', :git => 'https://github.com/hackiftekhar/IQKeyboardManager.git'
  pod 'PKHUD', :git => 'https://github.com/pkluz/PKHUD.git'
  pod 'Hero', :git => 'https://github.com/HeroTransitions/Hero.git'

  pod 'FirebaseAuth', :git => 'https://github.com/firebase/firebase-ios-sdk.git'
  pod 'FirebaseFirestore', :git => 'https://github.com/firebase/firebase-ios-sdk.git'
  pod 'FirebaseMessaging', :git => 'https://github.com/firebase/firebase-ios-sdk.git'
  
#  pod 'GoogleMLKit/BarcodeScanning'
#  pod 'GoogleMLKit/ObjectDetection'

  pod 'SideMenuSwift', :git => 'https://github.com/kukushi/SideMenu'
#  pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git'
#  pod 'EFNavigationBar', :git => 'https://github.com/EFPrefix/EFNavigationBar.git'
#  pod 'CryptoSwift', :git => 'https://github.com/krzyzanowskim/CryptoSwift.git'
#  pod 'L10n-swift', :git => 'https://github.com/Decybel07/L10n-swift.git'
#  pod 'ToastViewSwift', :git => 'https://github.com/BastiaanJansen/Toast-Swift.git'
#  pod 'SVProgressHUD'


# Pods for CinemaTix

  target 'CinemaTixTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CinemaTixUITests' do
    # Pods for testing
  end

end
